AWSTemplateFormatVersion: '2010-09-09'
Description: Launch EC2 instance and install Apache Tomcat 9

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: !Ref KeyName
      ImageId: ami-08a6efd148b1f7504  # Amazon Linux 2 (us-east-1)
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y java-11-openjdk
          curl -O https://downloads.apache.org/tomcat/tomcat-9/v9.0.83/bin/apache-tomcat-9.0.83.tar.gz
          mkdir -p /opt/tomcat
          tar xzvf apache-tomcat-9.0.83.tar.gz -C /opt/tomcat --strip-components=1
          chmod +x /opt/tomcat/bin/*.sh
          /opt/tomcat/bin/startup.sh

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0

Outputs:
  InstancePublicIP:
    Description: Public IP of the new EC2 instance
    Value: !GetAtt EC2Instance.PublicIp

  TomcatURL:
    Description: URL to access Tomcat
    Value: !Sub "http://${EC2Instance.PublicDnsName}:8080"
